
// Bootstrap file to trigger TypeScript type loading
// This file is auto-generated by LspManager

// Import main exports from @kubernetes/client-node
import * as k8s from '@kubernetes/client-node';

// Force TypeScript to resolve all exported types
export { k8s };

// Type references to ensure symbols are loaded
type _CoreApi = k8s.CoreV1Api;
type _AppsApi = k8s.AppsV1Api;
type _Config = k8s.KubeConfig;
