/**
 * Script module - Parse TypeScript scripts and extract metadata
 */

export type { CachedScript, ParseScriptsOptions } from './types.js';
export {
  parseScript,
  parseScriptsFromDirectory,
  isAutoGeneratedScriptName,
} from './script-parser.js';
